### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#1021]
I was finally able to run JAX in Windows.
But, it is Jaxlib 0.1.61 and  Jax 0.2.8 (expected to work with 0.2.9 too).
No GPU for now.
I used the following pre-compiled Windows jaxlib wheels:
https://github.com/erwincoumans/jax/releases/tag/winwhl-0.1.61

Now, my problem is that I can find a Numpyro version that will work with this versions of Jax.
Any suggestion? Thanks.

**Comment by fehiepsi** [comment]
@caxelrud I guess you can try to install some numpyro version and [ignore dependencies](https://stackoverflow.com/questions/12759761/python-pip-force-install-ignoring-dependencies).

**Comment by caxelrud** [comment]
Hi, I did install ignoring dependencies with:
`pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro --no-dependencies`

I tried the Eight Schools example and I got the following error: 
(By the way, I tried the notebooks from JAX documentation and they work in my Windows computer).

```
import numpyro

import numpyro.distributions as dist

import numpy as np

numpyro.set_platform("cpu")

J = 8

y = np.array([28.0, 8.0, -3.0, 7.0, -1.0, 1.0, 18.0, 12.0])
sigma = np.array([15.0, 10.0, 16.0, 11.0, 9.0, 11.0, 10.0, 18.0])


# Eight Schools example
def eight_schools(J, sigma, y=None):

     mu = numpyro.sample('mu', dist.Normal(0, 5))

     tau = numpyro.sample('tau', dist.HalfCauchy(5))

     with numpyro.plate('J', J):

         theta = numpyro.sample('theta', dist.Normal(mu, tau))

         numpyro.sample('obs', dist.Normal(theta, sigma), obs=y)


from jax import random
from numpyro.infer import MCMC, NUTS

nuts_kernel = NUTS(eight_schools)
mcmc = MCMC(nuts_kernel, num_warmup=500, num_samples=1000)
rng_key = random.PRNGKey(0)
mcmc.run(rng_key, J, sigma, y=y, extra_fields=('potential_energy',))


mcmc.run(rng_key, J, sigma, y=y, extra_fields=('potential_energy',))
Traceback (most recent call last):

  File "<ipython-input-3-5d1f91ec73c6>", line 1, in <module>
    mcmc.run(rng_key, J, sigma, y=y, extra_fields=('potential_energy',))

  File "C:\Users\User\anaconda3\lib\site-packages\numpyro\infer\mcmc.py", line 498, in run
    states_flat, last_state = partial_map_fn(map_args)

  File "C:\Users\User\anaconda3\lib\site-packages\numpyro\infer\mcmc.py", line 333, in _single_chain_mcmc
    init_state = self.sampler.init(rng_key, self.num_warmup, init_params,

  File "C:\Users\User\anaconda3\lib\site-packages\numpyro\infer\hmc.py", line 505, in init
    init_state = hmc_init_fn(init_params, rng_key)

  File "C:\Users\User\anaconda3\lib\site-packages\numpyro\infer\hmc.py", line 488, in <lambda>
    hmc_init_fn = lambda init_params, rng_key: self._init_fn(  # noqa: E731

  File "C:\Users\User\anaconda3\lib\site-packages\numpyro\infer\hmc.py", line 211, in init_kernel
    trajectory_length = lax.convert_element_type(trajectory_length, jnp.result_type(float))

  File "C:\Users\User\anaconda3\lib\site-packages\jax\_src\lax\lax.py", line 434, in convert_element_type
    return _device_put_raw(np.asarray(operand))

  File "C:\Users\User\anaconda3\lib\site-packages\jax\_src\lax\lax.py", line 1462, in _device_put_raw
    aval = raise_to_shaped(core.get_aval(x))

  File "C:\Users\User\anaconda3\lib\site-packages\jax\core.py", line 914, in get_aval
    return concrete_aval(x)

  File "C:\Users\User\anaconda3\lib\site-packages\jax\core.py", line 906, in concrete_aval
    if handler: return handler(x)

  File "C:\Users\User\anaconda3\lib\site-packages\jax\core.py", line 1101, in __init__
    assert self.dtype != np.dtype('O'), val

AssertionError: None
```
Let me know your recommendations. Thanks!

**Comment by fehiepsi** [comment]
@caxelrud Could you try `0.6` or `0.5` versions?
```
pip install numpyro==0.6 --no-dependencies
```
The latest version requires
```
        "jax>=0.2.11",
        "jaxlib>=0.1.62",
```

**Comment by caxelrud** [comment]
I installed Numpyro version 0.5 and now all Eight School example works.
I will test the other examples and let you know.

**Comment by caxelrud** [comment]
CPU and GPU version are working correctly in Windows.
I got few errors when testing the project's notebooks and Statistics Rethinking notebooks (and JAX notebooks).
I will reported here asap. It may be related to the version 0.50.
You can check the execution results at https://github.com/caxelrud/Research2021 .

**Comment by fehiepsi** [comment]
Great! For the old versions, you might need to choose one of the old commits of those tutorials. For now, we typically don't maintain backward compatibility for the old JAX versions.
