### ISSUE TITLE
TraceGraph_ELBO bug shape error

### ISSUE THREAD

**Issue by quattro** [pyro-ppl/numpyro#1131]
Hi, I've been running into a bug related to data with multiple likelihoods. It seems that when computing downstream costs in the TraceGraph, multiple children have an empty `frozenset` frames on line 389 of `elbo.py` resulting in shape mismatch due to lookup bugs in the `MultiFrameTensor`.

I have an example program [here](https://gist.github.com/quattro/c3cdf41bf52a2334aa2dd2851388d254) to recreate the issue. The example I provided is a trivial example where the data likelihoods are completely independent (and thus could be optimized separately), but this error also occurs in the situation when the data likelihoods are conditionally independent given some latent variable.

Ideally these types of situations would have another dimension to reflect different data settings with similarly structured likelihoods (and possible 'resolve' this issue naturally), but the shapes change per data type and don't work cleanly in a single tensor structure.

```
Traceback (most recent call last):
  File "/Users/nicholas/Projects/VAE_SuSiE/g_test.py", line 180, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/nicholas/Projects/VAE_SuSiE/g_test.py", line 166, in main
    results = svi.run(
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/svi.py", line 327, in run
    svi_state, loss = jit(body_fn)(svi_state, None)
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/svi.py", line 316, in body_fn
    svi_state, loss = self.stable_update(svi_state, *args, **kwargs)
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/svi.py", line 276, in stable_update
    (loss_val, mutable_state), optim_state = self.optim.eval_and_stable_update(
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/optim.py", line 93, in eval_and_stable_update
    (out, aux), grads = value_and_grad(fn, has_aux=True)(params)
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/svi.py", line 59, in loss_fn
    elbo.loss(
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/elbo.py", line 604, in loss
    return -single_particle_elbo(rng_key)
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/elbo.py", line 579, in single_particle_elbo
    downstream_costs, _ = _compute_downstream_costs(
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/elbo.py", line 483, in _compute_downstream_costs
    downstream_costs[node].add(*downstream_costs[child].items())
  File "/Users/nicholas/miniforge3/lib/python3.9/site-packages/numpyro/infer/elbo.py", line 389, in add
    self[frames] = self[frames] + value
  File "/Users/nicholas/Projects/jax/jax/_src/numpy/lax_numpy.py", line 5847, in deferring_binary_op
    return binary_op(self, other)
  File "/Users/nicholas/Projects/jax/jax/_src/numpy/lax_numpy.py", line 431, in fn
    return lax_fn(x1, x2) if x1.dtype != bool_ else bool_lax_fn(x1, x2)
TypeError: add got incompatible shapes for broadcasting: (2,), (4,).
```

**Comment by fehiepsi** [comment]
Hi @quattro, could you add `to_event` to the latent sites such as `Normal` (or put them under some `plate`)? I guess that causes the issue.

**Comment by quattro** [comment]
Hi @fehiepsi , apologies. While `to_event(1)` didn't seem to correct the issue, wrapping `beta~Normal` in a `plate` with `size=1` got it to run.

Would it be possible to catch and re-throw a more informative message in this setting (ie conditional independence is unclear)?

**Comment by fehiepsi** [comment]
That's a good point. I think we should throw errors when `plate` is missing. Looking at the code base, it is not clear to me where we should add the check. I'll follow up later. :)
