### ISSUE TITLE
Restart mcmc.run from the saved state of the previous session

### ISSUE THREAD

**Issue by ykawashima** [pyro-ppl/numpyro#1308]
I have a question regarding the MCMC. I see that it is possible to get multiple samples within the same session, as noted in [the NumPyro Docs](https://num.pyro.ai/en/0.6.0/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state), but is there any way to restart mcmc.run in another session with exactly the same settings as the previous one using the saved state? 

When I try to do something like this,
```
with open("output/last_state.pickle", mode='rb') as f:
    last_state = pickle.load(f)
mcmc.post_warmup_state = last_state
mcmc.run(mcmc.post_warmup_state.rng_key, y1=nflux)
```
I get the following error.
```
Traceback (most recent call last):
  File "restart.py", line 215, in <module>
    mcmc.run(mcmc.post_warmup_state.rng_key, y1=nflux)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 572, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 383, in _single_chain_mcmc
    collect_vals = fori_collect(
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/util.py", line 354, in fori_collect
    vals = jit(_body_fn)(i, vals)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/core.py", line 1560, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/core.py", line 1563, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 592, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 667, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1284, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1262, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/util.py", line 321, in _body_fn
    val = body_fun(val)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 174, in _sample_fn_nojit_args
    return (sampler.sample(state[0], args, kwargs),)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/hmc.py", line 760, in sample
    return self._sample_fn(state, model_args, model_kwargs)
jax._src.traceback_util.UnfilteredStackTrace: TypeError: 'NoneType' object is not callable

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "restart.py", line 215, in <module>
    mcmc.run(mcmc.post_warmup_state.rng_key, y1=nflux, init_params=samples)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 572, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 383, in _single_chain_mcmc
    collect_vals = fori_collect(
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/util.py", line 354, in fori_collect
    vals = jit(_body_fn)(i, vals)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/util.py", line 321, in _body_fn
    val = body_fun(val)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/mcmc.py", line 174, in _sample_fn_nojit_args
    return (sampler.sample(state[0], args, kwargs),)
  File "/home/kawashimayi/anaconda3/lib/python3.8/site-packages/numpyro-0.8.0-py3.8.egg/numpyro/infer/hmc.py", line 760, in sample
    return self._sample_fn(state, model_args, model_kwargs)
TypeError: 'NoneType' object is not callable
```
Thank you in advance!

**Comment by fehiepsi** [comment]
Looking like sample_fn is deleted. Do you pickle the mcmc object? By the way, it is better to use forum for questions. If you think this is a bug, could you provide small reproducible codes? I guess you might need to run `mcmc._compile(...)` but I'm not sure.

**Comment by ykawashima** [comment]
Thank you for your quick response. Yes, it is. Sorry that I forgot to mention, but what I pickle is the mcmc state object outputted with mcmc.last_state in the previous session. Ah sorry, I did not realize the forum. I will ask there. Thank you.

**Comment by fehiepsi** [comment]
Could you try `mcmc._compile(key, y1=nflux)` after loading your mcmc instance? Then you can setup post warm up state and run?

**Comment by ykawashima** [comment]
Thank you very much! It worked.
