### ISSUE TITLE
Error with log_likelihood with respect to random_flax_module

### ISSUE THREAD

**Issue by nirmalya-broad** [pyro-ppl/numpyro#1341]
I am getting error while using `log_likelihood` with respect to `random_flax_module`. Is this a bug or I am making any mistake?

my model:

```
from flax import linen as nn

class Net(nn.Module):
    n_units: int
    @nn.compact
    def __call__(self, x):
        x = nn.Dense(8)(x)  # Fist layer
        x = nn.relu(x)
        x = nn.Dense(8)(x)  # Middle layer
        x = nn.relu(x)
        x = nn.Dense(4)(x)  # Last layer
        return x

def model(X, Y = None, D_H = None, D_Y = 1):
    N, D_X = X.shape
    lclass = 4
    module = Net(n_units = D_H)
    net = random_flax_module("net", module, prior = dist.Normal(0, 1), input_shape = (N, D_X))
    # observe data
    lvals = net(X)
    with numpyro.plate("batch", X.shape[0]):
        numpyro.sample("Y", dist.Categorical(logits = lvals), obs = Y)
```
Inference:

```
def run_inference_DELTA(model, args, rng_key, X, Y, D_H):
    print("Starting DELTA inference")
    guide = AutoDelta( model)
    svi = SVI(model, guide, optim.Adam(0.001), Trace_ELBO())
    svi_result = svi.run(random.PRNGKey(100), args.svi_steps, X, Y, D_H)
    print("AutoDelta inference done")
    params = svi_result.params
    samples_1 = guide.sample_posterior(
        random.PRNGKey(1), params, sample_shape=(args.num_samples,)
    )
    return samples_1
   
def run_inference(model, args, rng_key, X, Y, D_H):
    return run_inference_DELTA(model, args, rng_key, X, Y, D_H)
 ```
   
Unfortunately I am getting error while using log_likelihood from  numpyro.infer.

```
 rng_key, rng_key_predict = random.split(random.PRNGKey(0))
 samples_1 = run_inference(model, args, rng_key, X_train, Y_train, D_H)
 ll = log_likelihood(model, samples_1, X = X_test, Y = Y_test, D_H = D_H)
```

The error is as follows:

```
  File "main.py", line 221, in main
    ll = log_likelihood(model, samples_1, X = X_test, Y = Y_test, D_H = D_H)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/util.py", line 1027, in log_likelihood
    return soft_vmap(single_loglik, posterior_samples, len(batch_shape), chunk_size)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/util.py", line 410, in soft_vmap
    ys = lax.map(fn, xs) if num_chunks > 1 else fn(xs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 2263, in map
    _, ys = scan(g, (), xs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1623, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1609, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/util.py", line 210, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/util.py", line 203, in cached
    return f(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 83, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/util.py", line 210, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/util.py", line 203, in cached
    return f(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 77, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1666, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1703, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 2262, in <lambda>
    g = lambda _, x: ((), f(x))
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/util.py", line 1002, in single_loglik
    model_trace = trace(substituted_model).get_trace(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/primitives.py", line 87, in __call__
    return self.fn(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/primitives.py", line 87, in __call__
    return self.fn(*args, **kwargs)
  File "main.py", line 68, in model
    net = random_flax_module("net", module, prior = dist.Normal(0, 1), input_shape = (N, D_X))
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/contrib/module.py", line 355, in random_flax_module
    nn = flax_module(
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/contrib/module.py", line 94, in flax_module
    nn_vars = flax.core.unfreeze(nn_module.init(rngs, *args, **kwargs))
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/flax/linen/module.py", line 1183, in init
    _, v_out = self.init_with_output(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/flax/linen/module.py", line 1152, in init_with_output
    return self.apply(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/flax/linen/module.py", line 1119, in apply
    return apply(
  File "/home/bandyopn/local/lib/python3.8/site-packages/flax/core/scope.py", line 803, in wrapper
    with bind(variables, rngs=rngs, mutable=mutable).temporary() as root:
  File "/home/bandyopn/local/lib/python3.8/site-packages/flax/core/scope.py", line 774, in bind
    raise errors.InvalidRngError(
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.InvalidRngError: rngs should be a dictionary mapping strings to `jax.PRNGKey`. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.InvalidRngError)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 271, in <module>
    main(args)
  File "main.py", line 221, in main
    ll = log_likelihood(model, samples_1, X = X_test, Y = Y_test, D_H = D_H)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/util.py", line 1027, in log_likelihood
    return soft_vmap(single_loglik, posterior_samples, len(batch_shape), chunk_size)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/util.py", line 410, in soft_vmap
    ys = lax.map(fn, xs) if num_chunks > 1 else fn(xs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/util.py", line 1002, in single_loglik
    model_trace = trace(substituted_model).get_trace(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/primitives.py", line 87, in __call__
    return self.fn(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/primitives.py", line 87, in __call__
    return self.fn(*args, **kwargs)
  File "main.py", line 68, in model
    net = random_flax_module("net", module, prior = dist.Normal(0, 1), input_shape = (N, D_X))
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/contrib/module.py", line 355, in random_flax_module
    nn = flax_module(
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/contrib/module.py", line 94, in flax_module
    nn_vars = flax.core.unfreeze(nn_module.init(rngs, *args, **kwargs))
flax.errors.InvalidRngError: rngs should be a dictionary mapping strings to `jax.PRNGKey`. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.InvalidRngError)
```

**Comment by fehiepsi** [comment]
Hi @nirmalya-broad, because you are not providing params to your model, we will need to initialize the parameters (to get random keys, you can do `seed_model = numpyro.handlers.seed(model, rng_seed=0)`). In this case, you already get optimized parameters, so you can use log likelihood with `optimized_model = numpyro.handlers.substitute(model, data=params)`

**Comment by nirmalya-broad** [comment]
Hi @fehiepsi, Yes, that worked! Thank you very much.

The following code is adapted from https://num.pyro.ai/en/stable/handlers.html

```
def log_likelihood(rng_key, params, model, *args, **kwargs):
    model = handlers.substitute(handlers.seed(model, rng_key), params)
    model_trace = handlers.trace(model).get_trace(*args, **kwargs)
    obs_node = model_trace['Y']
    return obs_node['fn'].log_prob(obs_node['value'])

def log_likelihood_all(rng_key, params, model, *args, **kwargs):
    n = list(params.values())[0].shape[0]
    log_lk_fn = vmap(lambda rng_key, params: log_likelihood(rng_key, params, model, *args, **kwargs))
    log_lk_vals = log_lk_fn(random.split(rng_key, n), params)
    return log_lk_vals
    
ll_all = log_likelihood_all(random.PRNGKey(2), samples_1,
      model, X_test, Y_test)
```

**Comment by fehiepsi** [comment]
Hi @nirmalya-broad, by `params`, I meant it is `svi_result.params`. I guess with the change in my last comment, you can use `log_likelihood` utility directly with `optimized_model`.

**Comment by fehiepsi** [comment]
Closed due to the issue is resolved.
