### ISSUE TITLE
random_flax_module with NeuTraReparam is not working

### ISSUE THREAD

**Issue by nirmalya-broad** [pyro-ppl/numpyro#1414]
This is my model:

```

class Net(nn.Module):
    n_units: int

    @nn.compact
    def __call__(self, x):
        x = nn.Dense(8)(x)  # Fist layer
        x = nn.relu(x)
        x = nn.Dense(8)(x)  # Middle layer
        x = nn.relu(x)
        x = nn.Dense(4)(x)  # Last layer
        return x

def model(X, Y = None, D_H = None, D_Y = 1):
    N, D_X = X.shape
    lclass = 4

    module = Net(n_units = D_H)
    net = random_flax_module("net", module, prior = (
                            lambda name, shape:
                                dist.Cauchy() if "bias" in name
                                else dist.Normal(0, 1)),
                            input_shape = (N, D_X))
    # observe data
    lvals = net(X)
    with numpyro.plate("batch", X.shape[0]):
        numpyro.sample("Y", dist.Categorical(logits = lvals), obs = Y)
```

I am trying to use NeuTra with NUTS:

```
def run_inference_NUTS_NeuTraReparam(model, args, rng_key, X, Y, D_H):
    start = time.time()

    guide = AutoBNAFNormal(
        model, hidden_factors=[args.hidden_factor, args.hidden_factor]
    )
    svi = SVI(model, guide, optim.Adam(0.001), Trace_ELBO())
    print("Start training guide...")
    svi_result = svi.run(random.PRNGKey(2), args.svi_steps, X, Y, D_H)
    print("Finish training guide. Extract samples...")
    guide_samples_1 = guide.sample_posterior(
        random.PRNGKey(500), svi_result.params,
        sample_shape=(args.num_samples,))
    print(guide_samples_1)
    guide_samples = guide_samples_1.copy()

    print("\nStart NeuTra HMC...")
    neutra = NeuTraReparam(guide, svi_result.params)
    neutra_model = neutra.reparam(model)
    print("........")
    tr = numpyro.handlers.trace(handlers.seed(model, random.PRNGKey(0))).get_trace(X, Y, D_H)
    print("printing trace")
    print(tr)
    print("........")

    neutra_tr = numpyro.handlers.trace(handlers.seed(neutra_model, random.PRNGKey(0))).get_trace(X, Y, D_H)
    print("printing neutra_model trace")
    print(neutra_tr)
    print("........")

    kernel = NUTS(neutra_model)
    mcmc = MCMC(
        kernel,
        num_warmup=args.num_warmup,
        num_samples=args.num_samples,
        num_chains=args.num_chains,
        progress_bar=False if "NUMPYRO_SPHINXBUILD" in os.environ else True,
    )
    mcmc.run(rng_key, X, Y, D_H)
    mcmc.print_summary()
    print("\nMCMC elapsed time:", time.time() - start)
    samples_0 =  mcmc.get_samples()
    print("Transform samples into unwarped space...")
    samples_1 = neutra.transform_sample(samples_0)["net/auto_shared_latent"]
    print("Printing summary of samples")
    print_summary(samples_1)

    return samples_1
```

I am getting the following error:

```
MCMC elapsed time: 337.09593892097473
Transform samples into unwarped space...
Traceback (most recent call last):
  File "main.py", line 404, in <module>
    main(args)
  File "main.py", line 286, in main
    samples_1 = run_inference(model, args, rng_key, X_train, Y_train, D_H)
  File "main.py", line 219, in run_inference
    return run_inference_NUTS_NeuTraReparam(model, args, rng_key, X, Y, D_H)
  File "main.py", line 151, in run_inference_NUTS_NeuTraReparam
    samples_1 = neutra.transform_sample(samples_0)["net/auto_shared_latent"]
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/reparam.py", line 291, in transform_sample
    x_unconstrained = self.transform(latent)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/transforms.py", line 267, in __call__
    x = part(x)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/flows.py", line 116, in __call__
    return self.call_with_intermediates(x)[0]
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/flows.py", line 119, in call_with_intermediates
    y, logdet = self.bn_arn(x)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/nn/block_neural_arn.py", line 203, in apply_fun
    out, logdet = arn[1](params, (inputs, None), **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/example_libraries/stax.py", line 302, in apply_fun
    inputs = fun(param, inputs, rng=rng, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/nn/block_neural_arn.py", line 84, in apply_fun
    out = jnp.dot(x, w)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/api.py", line 427, in cache_miss
    out_flat = xla.xla_call(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/core.py", line 1690, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/core.py", line 1702, in call_bind
    outs = top_trace.process_call(primitive, fun, tracers, params)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/core.py", line 601, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 142, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 169, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 197, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1726, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1703, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 4856, in dot
    _check_arraylike("dot", a, b)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 570, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: dot requires ndarray or scalar arguments, got <class 'dict'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 404, in <module>
    main(args)
  File "main.py", line 286, in main
    samples_1 = run_inference(model, args, rng_key, X_train, Y_train, D_H)
  File "main.py", line 219, in run_inference
    return run_inference_NUTS_NeuTraReparam(model, args, rng_key, X, Y, D_H)
  File "main.py", line 151, in run_inference_NUTS_NeuTraReparam
    samples_1 = neutra.transform_sample(samples_0)["net/auto_shared_latent"]
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/infer/reparam.py", line 291, in transform_sample
    x_unconstrained = self.transform(latent)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/transforms.py", line 267, in __call__
    x = part(x)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/flows.py", line 116, in __call__
    return self.call_with_intermediates(x)[0]
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/distributions/flows.py", line 119, in call_with_intermediates
    y, logdet = self.bn_arn(x)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/nn/block_neural_arn.py", line 203, in apply_fun
    out, logdet = arn[1](params, (inputs, None), **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/example_libraries/stax.py", line 302, in apply_fun
    inputs = fun(param, inputs, rng=rng, **kwargs)
  File "/home/bandyopn/local/lib/python3.8/site-packages/numpyro/nn/block_neural_arn.py", line 84, in apply_fun
    out = jnp.dot(x, w)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 4856, in dot
    _check_arraylike("dot", a, b)
  File "/home/bandyopn/local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 570, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: dot requires ndarray or scalar arguments, got <class 'dict'> at position 0.

```

Could you please give me any suggestion regarding the error  at **samples_1 = neutra.transform_sample(samples_0)["net/auto_shared_latent"]**

Thank you.

**Comment by fehiepsi** [comment]
Could you provide some reproducible code? I think some information in the `print` statements in your code will be helpful (like keys of the traces). The error looks like `samples_0` is expected to be an array, but a dictionary is provided.

**Comment by nirmalya-broad** [comment]
Sure, let me work on that. I shall sent it by the end of tomorrow.
