### ISSUE TITLE
With the latest NumPy version (1.23.0) MCMC inference throws KeyError: dtype([('float0', 'V')])

### ISSUE THREAD

**Issue by german-borisevich** [pyro-ppl/numpyro#1439]
After reinstalling numpyro into fresh virtualenv, I tried running MCMC inference on the following code:
```
import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS
from jax.random import PRNGKey
import jax.numpy as jnp

# Data
a = [63, 66]
b = [24, 35]

def beta_binomial(a, b):
    def model():
        with numpyro.plate("groups", 2):
            probs = numpyro.sample("theta", dist.Beta(1, 1))
        with numpyro.plate("data", 2):
            numpyro.sample("obs", dist.Binomial(a, probs), obs=b)
    return model

model = beta_binomial(jnp.array(a), jnp.array(b))
kernel = NUTS(model)
mcmc = MCMC(
    sampler=kernel,
    num_warmup=2500,
    num_samples=5000,
    num_chains=3,
    chain_method="sequential",
    progress_bar=True,
)
mcmc.run(rng_key=PRNGKey(10))
mcmc.print_summary()
```

After that the following Traceback received:
```
Traceback (most recent call last):
  File "/Users/user/Desktop/Script Testing/test.py", line 41, in <module>
    mcmc.run(rng_key=PRNGKey(10))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 597, in run
    states, last_state = _laxmap(partial_map_fn, map_args)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 160, in _laxmap
    ys.append(f(x))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 381, in _single_chain_mcmc
    init_state = self.sampler.init(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 706, in init
    init_params = self._init_state(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 652, in _init_state
    init_params, potential_fn, postprocess_fn, model_trace = initialize_model(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 654, in initialize_model
    (init_params, pe, grad), is_valid = find_valid_initial_params(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 395, in find_valid_initial_params
    (init_params, pe, z_grad), is_valid = _find_valid_params(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 381, in _find_valid_params
    _, _, (init_params, pe, z_grad), is_valid = init_state = body_fn(init_state)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 366, in body_fn
    pe, z_grad = value_and_grad(potential_fn)(params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/api.py", line 982, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/api.py", line 2441, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/ad.py", line 129, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/ad.py", line 116, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 606, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 248, in potential_energy
    log_joint, model_trace = log_density_(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 62, in log_density
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/Users/user/Desktop/Script Testing/test.py", line 22, in model
    probs = numpyro.sample("theta", dist.Beta(1, 1))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 219, in sample
    msg = apply_stack(initial_msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 47, in apply_stack
    handler.process_message(msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/handlers.py", line 789, in process_message
    value = self.substitute_fn(msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 216, in _unconstrain_reparam
    log_det = t.log_abs_det_jacobian(p, value)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/distributions/transforms.py", line 816, in log_abs_det_jacobian
    return -softplus(x) - softplus(-x)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/api.py", line 466, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1771, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1787, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/ad.py", line 344, in process_call
    result = call_primitive.bind(f_jvp, *primals, *nonzero_tangents, **new_params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1771, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1787, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 216, in process_call
    out = primitive.bind(_update_annotation(f_, f.in_type, in_knowns),
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1771, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 1787, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/core.py", line 660, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dispatch.py", line 149, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dispatch.py", line 197, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dispatch.py", line 228, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1844, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/nn/functions.py", line 66, in softplus
    return jnp.logaddexp(x, 0)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 226, in __call__
    out_flat = custom_jvp_call_p.bind(flat_fun, flat_jvp, *args_flat)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 289, in bind
    outs = top_trace.process_custom_jvp_call(self, fun, jvp, tracers)  # type: ignore
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/interpreters/ad.py", line 377, in process_custom_jvp_call
    outs = f_jvp.call_wrapped(*it.chain(primals_in, tangents_in))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 361, in _logaddexp_jvp
    x1, x2, t1, t2 = _promote_args_inexact("logaddexp_jvp", x1, x2, t1, t2)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 327, in _promote_args_inexact
    return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 262, in _promote_dtypes_inexact
    to_dtype, weak_type = dtypes._lattice_result_type(*args)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dtypes.py", line 373, in _lattice_result_type
    result_type = _least_upper_bound(*{_jax_type(d, w) for d, w in zip(dtypes, weak_types)})
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dtypes.py", line 311, in _least_upper_bound
    CUB = set.intersection(*(UB[n] for n in N))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/dtypes.py", line 311, in <genexpr>
    CUB = set.intersection(*(UB[n] for n in N))
jax._src.traceback_util.UnfilteredStackTrace: KeyError: dtype([('float0', 'V')])

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Desktop/Script Testing/test.py", line 41, in <module>
    mcmc.run(rng_key=PRNGKey(10))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 597, in run
    states, last_state = _laxmap(partial_map_fn, map_args)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 160, in _laxmap
    ys.append(f(x))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 381, in _single_chain_mcmc
    init_state = self.sampler.init(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 706, in init
    init_params = self._init_state(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 652, in _init_state
    init_params, potential_fn, postprocess_fn, model_trace = initialize_model(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 654, in initialize_model
    (init_params, pe, grad), is_valid = find_valid_initial_params(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 395, in find_valid_initial_params
    (init_params, pe, z_grad), is_valid = _find_valid_params(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 381, in _find_valid_params
    _, _, (init_params, pe, z_grad), is_valid = init_state = body_fn(init_state)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 366, in body_fn
    pe, z_grad = value_and_grad(potential_fn)(params)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 248, in potential_energy
    log_joint, model_trace = log_density_(
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 62, in log_density
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/Users/user/Desktop/Script Testing/test.py", line 22, in model
    probs = numpyro.sample("theta", dist.Beta(1, 1))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 219, in sample
    msg = apply_stack(initial_msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/primitives.py", line 47, in apply_stack
    handler.process_message(msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/handlers.py", line 789, in process_message
    value = self.substitute_fn(msg)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/infer/util.py", line 216, in _unconstrain_reparam
    log_det = t.log_abs_det_jacobian(p, value)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/numpyro/distributions/transforms.py", line 816, in log_abs_det_jacobian
    return -softplus(x) - softplus(-x)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/nn/functions.py", line 66, in softplus
    return jnp.logaddexp(x, 0)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 361, in _logaddexp_jvp
    x1, x2, t1, t2 = _promote_args_inexact("logaddexp_jvp", x1, x2, t1, t2)
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 327, in _promote_args_inexact
    return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))
  File "/Users/user/.pyenv/versions/venv/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 262, in _promote_dtypes_inexact
    to_dtype, weak_type = dtypes._lattice_result_type(*args)
KeyError: dtype([('float0', 'V')])
```

After trials and errors I have discovered that installing older version of NumPy (e.g. 1.22.3) helps.
Local machine is MacBook Pro with M1 Pro, macOS Monterey 12.4.

_P.S. This this my first post on GitHub, so I'm not sure if this the correct repo where I should post it._

**Comment by fehiepsi** [comment]
Thanks @german-borisevich! I guess this jax issue is relevant https://github.com/google/jax/issues/11238

**Comment by fehiepsi** [comment]
This is fixed upstream. Please check out the the next jax release or reopen this if needed.
