### ISSUE TITLE
Apple Metal Support

### ISSUE THREAD

**Issue by buchholzmd** [pyro-ppl/numpyro#1660]
Hi,

Now that [JAX has apple M1/M2 support](https://developer.apple.com/metal/jax/), I was wondering if there were any plans for a release supporting as well.

Thanks!

**Comment by fehiepsi** [comment]
Can you install an old version of numpyro with it?

**Comment by buchholzmd** [comment]
Ok, I think I was confused and thought that I would need to specify the architecture like you do for cuda:

`pip install numpyro[cuda] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html'

If I first install `jax-metal` and then subsequently install numpyro, it appears to have installed a compatible version (0.12.1).
Another thing that concerned me is to specify the device in jax-metal you need to do:

`_ = jax.device_put(jax.numpy.ones(1), device=jax.devices('METAL')[0])`

I am new to NumPyro and thought that may cause issues, in any cases that NumPyro isn't detecting the device automatically. Seems to be working though, and I'll close the issue and create something new if I run into any future problems.

**Comment by fehiepsi** [comment]
I think NumPyro does not introduce custom device handling. It's surprised to me that  NumPyro isn't detecting the device automatically while native jax code does. I think you can look for how to specify default devices in apple metal forum. Please feel free to reopen the issue if it turns out to be a numpyro problem.

**Comment by nikisix** [comment]
I installed jax-metal on top of numpyro `0.12.1` and am breaking on both examples I tried. Below are the links to the example with their corresponding error message. Example 2 admittedly breaks on tf_prob code, but including anyways.

https://num.pyro.ai/en/stable/tutorials/bayesian_hierarchical_linear_regression.html
```
Traceback (most recent call last):
  File "~/envs/jax-metal/benchmark/linreg.py", line 52, in <module>
    mcmc.run(rng_key, patient_code, Weeks, FVC_obs=FVC_obs)
  File "~/envs/jax-metal/lib/python3.11/site-packages/numpyro/infer/mcmc.py", line 628, in run
    states_flat, last_state = partial_map_fn(map_args)
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/numpyro/infer/mcmc.py", line 434, in _single_chain_mcmc
    collect_vals = fori_collect(
                   ^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/numpyro/util.py", line 358, in fori_collect
    vals = jit(_body_fn)(i, vals)
           ^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: ~/envs/jax-metal/lib/python3.11/site-packages/numpyro/infer/hmc_util.py:939:77: error: failed to legalize operation 'mhlo.shift_right_arithmetic'
        lambda nc: nc[0] > 0, lambda nc: (nc[0] >> 1, nc[1] + (nc[0] & 1)), (n >> 1, 0)
```

https://num.pyro.ai/en/stable/examples/hsgp.html
```
  File "~/envs/jax-metal/benchmark/hsgp.py", line 236, in approx_periodic_gp_ncp
    q2 = diag_spectral_density_periodic(alpha, length, M)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/benchmark/hsgp.py", line 200, in diag_spectral_density_periodic
    q2 = (c * alpha**2 / jnp.exp(a)) * modified_bessel_first_kind(J, a)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/benchmark/hsgp.py", line 188, in modified_bessel_first_kind
    return jnp.exp(jnp.abs(z)) * tfp.math.bessel_ive(v, z)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 1018, in bessel_ive
    return _bessel_ive_custom_gradient(v, z)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 989, in _bessel_ive_custom_gradient
    return _bessel_ive_naive(v, z)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 934, in _bessel_ive_naive
    return _bessel_ive_shared(v, z, output_log_space=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 897, in _bessel_ive_shared
    temme_ive = _temme_expansion(
                ^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 784, in _temme_expansion
    temme_kue, temme_kuep1 = _temme_series(
                             ^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/math/bessel.py", line 582, in _temme_series
    tol = tf.cast(np.finfo(numpy_dtype).eps, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/_utils.py", line 62, in wrap
    return new_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 410, in <lambda>
    lambda x, dtype, name=None: _cast(x, utils.numpy_dtype(dtype)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 401, in _cast
    x = convert_to_tensor(x)
        ^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/_utils.py", line 62, in wrap
    return new_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 167, in _convert_to_tensor
    ret = conversion_func(value, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/jax-metal/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 222, in _default_convert_to_tensor
    value.dtype, jax.dtypes.prng_key
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'jax.dtypes' has no attribute 'prng_key'
```
