### ISSUE TITLE
PyTorch model with `custom_jvp` doesn't work with NUTS

### ISSUE THREAD

**Issue by danjenson** [pyro-ppl/numpyro#1668]
Here is some sample code:
```python
#!/usr/bin/env python3
import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist
import torch
import torch.nn as nn
from jax import custom_jvp
from numpyro.infer import MCMC, NUTS
from torch import nn


class Simple(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.m = nn.Linear(dim, dim)

    def forward(self, z):
        return self.m(z)


def wrap_torch(model_pt):
    @custom_jvp
    def f(x):
        with torch.no_grad():
            return jnp.array(model_pt(torch.tensor(np.copy(x))))

    @f.defjvp
    def f_jvp(primals, tangents):
        (x,), (x_dot,) = primals, tangents
        result_shape = jax.core.ShapedArray((x.shape[0], 2), x.dtype)
        out = jax.pure_callback(cbk, result_shape, x, x_dot)
        return out[:, 0], out[:, 1]

    def cbk(x, x_dot):
        x_pt = torch.tensor(np.copy(x), requires_grad=True)
        out_pt = model_pt(x_pt)
        out_pt.sum().backward()
        primal_out = jnp.array(out_pt.detach().numpy())
        tangent_out = jnp.array(x_pt.grad) * x_dot
        model_pt.zero_grad()
        return jnp.array([primal_out, tangent_out]).T

    return f


def numpyro_model(y, z_to_f):
    n = len(y)
    z = numpyro.sample("z", dist.Normal(jnp.zeros(n), jnp.ones(n)))
    f = numpyro.deterministic("f", z_to_f(z))
    y = numpyro.sample("y", dist.Normal(f, 0.1), obs=y)


if __name__ == "__main__":
    y = jnp.array([5.0, 4.0, 3.0, 2.0])
    model = Simple(len(y))
    z_to_f = wrap_torch(model)
    kernel = NUTS(numpyro_model)
    mcmc = MCMC(kernel, num_warmup=10, num_samples=10)
    mcmc.run(y=y, z_to_f=z_to_f, rng_key=jax.random.PRNGKey(0))
```

Running this yields the following:
```bash
λ JAX_TRACEBACK_FILTERING=off python t.py
Traceback (most recent call last):
  File "/data/scratch/t.py", line 61, in <module>
    mcmc.run(y=y, z_to_f=z_to_f, rng_key=jax.random.PRNGKey(0))
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/mcmc.py", line 634, in run
    states_flat, last_state = partial_map_fn(map_args)
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/mcmc.py", line 416, in _single_chain_mcmc
    new_init_state = self.sampler.init(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/hmc.py", line 713, in init
    init_params = self._init_state(
                  ^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/hmc.py", line 657, in _init_state
    ) = initialize_model(
        ^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/util.py", line 703, in initialize_model
    (init_params, pe, grad), is_valid = find_valid_initial_params(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/util.py", line 440, in find_valid_initial_params
    (init_params, pe, z_grad), is_valid = _find_valid_params(
                                          ^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/util.py", line 426, in _find_valid_params
    _, _, (init_params, pe, z_grad), is_valid = init_state = body_fn(init_state)
                                                             ^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/numpyro/infer/util.py", line 410, in body_fn
    pe, z_grad = value_and_grad(potential_fn)(params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 177, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/api.py", line 732, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/api.py", line 2238, in _vjp
    out_primal, out_vjp = ad.vjp(
                          ^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/interpreters/ad.py", line 140, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/interpreters/ad.py", line 131, in linearize
    assert all(out_primal_pval.is_known() for out_primal_pval in out_primals_pvals)
AssertionError
```

**Comment by martinjankowiak** [comment]
you appear to be indiscriminately mixing jax/numpyro with pytorch/pyro. this is not allowed. these are separate ecosystems and you need to commit to consistently using one or the other.

**Comment by danjenson** [comment]
I want to use a pre-trained torch model as a deterministic function in JAX. Is there no way to do that?

**Comment by danjenson** [comment]
Also, this code appears to be running...although I am not sure I have correctly implemented `f_bwd`:
```python
#!/usr/bin/env python3
import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist
import torch
import torch.nn as nn
from jax import custom_vjp, jit
from numpyro.infer import MCMC, NUTS
from torch import nn


class Simple(nn.Module):
    def __init__(self, z_dim, y_dim):
        super().__init__()
        self.m = nn.Linear(z_dim, y_dim)

    def forward(self, z):
        return self.m(z)


def wrap_torch(model, z_dim, y_dim):
    def torch_infer(x):
        with torch.no_grad():
            return jnp.array(model(torch.tensor(np.copy(x))))

    def torch_grad(x):
        x_pt = torch.tensor(np.copy(x), requires_grad=True)
        model(x_pt).sum().backward()
        return jnp.array(x_pt.grad)

    @custom_vjp
    def f(x):
        return jax.pure_callback(
            torch_infer, jax.ShapeDtypeStruct((y_dim,), x.dtype), x
        )

    def f_fwd(x):
        return f(x), (x,)

    def f_bwd(res, g):
        (x,) = res
        grad = jax.pure_callback(torch_grad, jax.ShapeDtypeStruct((z_dim,), x.dtype), x)
        # return (grad,)
        return (jnp.outer(grad, g).sum(axis=1),)

    f.defvjp(f_fwd, f_bwd)

    return f


def numpyro_model(y, z_to_f, z_dim):
    z = numpyro.sample("z", dist.Normal(jnp.zeros(z_dim), jnp.ones(z_dim)))
    f = numpyro.deterministic("f", z_to_f(z))
    y = numpyro.sample("y", dist.Normal(f, 0.1), obs=y)


if __name__ == "__main__":
    z_dim, y_dim = 3, 4
    key = jax.random.PRNGKey(0)
    y = jax.random.normal(key, shape=(y_dim,))
    model = Simple(z_dim, y_dim)
    z_to_f = wrap_torch(model, z_dim, y_dim)
    kernel = NUTS(numpyro_model)
    mcmc = MCMC(kernel, num_warmup=100, num_samples=100)
    mcmc.run(y=y, z_to_f=z_to_f, z_dim=z_dim, rng_key=jax.random.PRNGKey(0))
```

**Comment by martinjankowiak** [comment]
if your jax code is correctly implemented you should be able to use it in numpyro. you may need to pass `forward_mode_differentiation=True` to your NUTS instance; see docs.

**Comment by fehiepsi** [comment]
I guess the problem has been resolved.
