### ISSUE TITLE
Pin jaxlib version in next release

### ISSUE THREAD

**Issue by kalradivyanshu** [pyro-ppl/numpyro#281]
Hey,

I was following: http://pyro.ai/numpyro/bayesian_regression.html, and tried to run the following code:

```
import jax
import jax.numpy as np
from jax import random, vmap
from jax.config import config; config.update("jax_platform_name", "cpu")
from jax.scipy.special import logsumexp
import matplotlib
import matplotlib.pyplot as plt
import numpy as onp
import pandas as pd
import seaborn as sns

from numpyro.diagnostics import hpdi
import numpyro.distributions as dist
from numpyro.handlers import sample, seed, substitute, trace
from numpyro.hmc_util import initialize_model
from numpyro.mcmc import mcmc

%matplotlib inline
plt.style.use('bmh')
plt.rcParams.update({'font.size': 16,
                     'xtick.labelsize': 14,
                     'ytick.labelsize': 14,
                     'axes.titlesize': 'large',
                     'axes.labelsize': 'medium'})
```

and it gave the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-2f9c08a220e0> in <module>
     12 
     13 from numpyro.diagnostics import hpdi
---> 14 import numpyro.distributions as dist
     15 from numpyro.handlers import sample, seed, substitute, trace
     16 from numpyro.hmc_util import initialize_model

/usr/local/lib/python3.6/site-packages/numpyro/distributions/__init__.py in <module>
----> 1 from numpyro.distributions.continuous import (
      2     Beta,
      3     Cauchy,
      4     Chi2,
      5     Dirichlet,

/usr/local/lib/python3.6/site-packages/numpyro/distributions/continuous.py in <module>
     29 from jax.scipy.special import gammaln, log_ndtr, ndtr, ndtri
     30 
---> 31 from numpyro.distributions import constraints
     32 from numpyro.distributions.constraints import AbsTransform, AffineTransform, ExpTransform
     33 from numpyro.distributions.distribution import Distribution, TransformedDistribution

/usr/local/lib/python3.6/site-packages/numpyro/distributions/constraints.py in <module>
     26 from jax.scipy.special import expit, logit
     27 
---> 28 from numpyro.distributions.util import cumprod, cumsum, matrix_to_tril_vec, signed_stick_breaking_tril, sum_rightmost
     29 
     30 ##########################################################

/usr/local/lib/python3.6/site-packages/numpyro/distributions/util.py in <module>
    179 
    180 
--> 181 ad.defjvp2(_standard_gamma_p.primitive, None,
    182            lambda tangent, sample, key, alpha, **kwargs: tangent * _standard_gamma_grad(sample, alpha))
    183 batching.defvectorized(_standard_gamma_p.primitive)

AttributeError: 'CustomTransformsFunction' object has no attribute 'primitive'
```

Can you let me know why this is happening? Thanks.

**Comment by neerajprad** [comment]
Could you check what is the version of numpyro and jax that you are using? I think there is probably a mismatch in the numpyro and jax / jaxlib versions. A quick fix might just be to install from source instead of using pip.

**Comment by kalradivyanshu** [comment]
Importing jax actually gives me an error

```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *
  File "/usr/local/lib/python3.6/site-packages/jax/api.py", line 50, in <module>
    from .lib.xla_bridge import canonicalize_dtype, device_count
  File "/usr/local/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 57, in <module>
    from jaxlib import xla_data_pb2
ImportError: cannot import name 'xla_data_pb2'
>>> import jaxlib
>>> jaxlib.__version__
'0.1.23'
>>> import numpyro
>>> numpyro.__version__
'0.1.0'
```

**Comment by neerajprad** [comment]
I think you are using a more recent version of jaxlib that is incompatible with the jax version that numpyro release depends on. You can downgrade jaxlib by doing `pip install jaxlib==0.1.14` (may not work on all platforms):

Pinning the versions as below will be compatible with NumPyro release.
```
jax==0.1.35
jaxlib==0.1.14
```

**TODOs for next release:**

 - [ ] If we are pinning jax version, we should also pin the jaxlib version in setup.py.
 - [ ] Assert on the numpyro version number in tutorials as in Pyro.

**Comment by kalradivyanshu** [comment]
Yup, downgrading jaxlib, made it work, thanks!

**Comment by fehiepsi** [comment]
Closed! We currently pinned jaxlib to a fixed version. Will relax it again after the release.
