### ISSUE TITLE
error when running minipyro.py example: data type "guide_loc" not understood

### ISSUE THREAD

**Issue by timnon** [pyro-ppl/numpyro#346]
I get the following error when running `minipyro.py` from the example folder with version `0.2.0`:
```
/opt/anaconda3/lib/python3.7/site-packages/jax/lib/xla_bridge.py:114: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "minipyro.py", line 69, in <module>
    main(args)
  File "minipyro.py", line 48, in main
    svi_state = fori_loop(0, args.num_steps, body_fn, svi_state)
  File "/opt/anaconda3/lib/python3.7/site-packages/numpyro/util.py", line 72, in fori_loop
    return lax.fori_loop(lower, upper, body_fun, init_val)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 118, in fori_loop
    _, result = while_loop(while_cond_fun, while_body_fun, (lower, init_val))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 161, in while_loop
    body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(body_fun, in_tree, init_avals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 56, in _initial_style_jaxpr
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(fun, in_pvals, instantiate=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 318, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 116, in while_body_fun
    return lax.add(i, lax._const(i, 1)), body_fun(i, x)
  File "minipyro.py", line 45, in body_fn
    svi_state, loss = svi.update(val, model_args=(data,))
  File "/opt/anaconda3/lib/python3.7/site-packages/numpyro/svi.py", line 261, in update
    model_args, guide_args, self.kwargs))(params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/api.py", line 386, in value_and_grad_f
    ans, vjp_py = vjp(f_partial, *dyn_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/api.py", line 1046, in vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 105, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 94, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 318, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/numpyro/svi.py", line 261, in <lambda>
    model_args, guide_args, self.kwargs))(params)
  File "minipyro.py", line 37, in loss
    rng = random.split(rng, num_particles)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/random.py", line 193, in split
    return _split(key, num)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/api.py", line 147, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device_assignment=device_assignment, backend=backend)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 232, in process_call
    result = call_primitive.bind(f_jvp, *(primals + nonzero_tangents), **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 113, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 113, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 569, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 366, in _xla_call_impl
    *map(abstractify, args))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 217, in cached_fun
    ans, f_prev = cached_fun_body(f, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 214, in cached_fun_body
    return call(f, *args), f
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 380, in _xla_callable
    jaxpr, (pvals, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/random.py", line 198, in _split
    return lax.reshape(threefry_2x32(key, counts), (num, 2))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/api.py", line 147, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device_assignment=device_assignment, backend=backend)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 232, in process_call
    result = call_primitive.bind(f_jvp, *(primals + nonzero_tangents), **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 113, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 113, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 572, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 113, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/core.py", line 569, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 366, in _xla_call_impl
    *map(abstractify, args))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 217, in cached_fun
    ans, f_prev = cached_fun_body(f, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 214, in cached_fun_body
    return call(f, *args), f
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 380, in _xla_callable
    jaxpr, (pvals, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/random.py", line 107, in threefry_2x32
    if not lax.dtype(key1) == lax.dtype(key2) == lax.dtype(count) == onp.uint32:
TypeError: data type "guide_loc" not understood
```

**Comment by neerajprad** [comment]
I think the SVI code (in particular, the ELBO loss) was recently changed so the example that you see on the master branch will need NumPyro's current master branch to run. 

You can run the earlier version of the tutorial by checking out the 0.2 tag `git checkout v0.2.0`, which should run fine with NumPyro's 0.2 install. Alternatively you can run the example code in the master branch but you'll need to install NumPyro from source and use the current jax/jaxlib versions.

**Comment by timnon** [comment]
Thanks, the old version works.
