### ISSUE TITLE
JAX 0.1.58 support

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#533]
Hi, it seems that latest jax 0.1.58 has some API breaking changes that breaks numpyro. Just wanted to post it here. It would be very nice to be able to use it.

```bash
>>> import numpyro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jerrhe/Dropbox/Projects/SafeRew/numpyro/numpyro/__init__.py", line 1, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, optim
  File "/home/jerrhe/Dropbox/Projects/SafeRew/numpyro/numpyro/diagnostics.py", line 9, in <module>
    from jax import device_get
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jax/api.py", line 44, in <module>
    from . import ad_util
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jax/ad_util.py", line 20, in <module>
    from .tree_util import register_pytree_node
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jax/tree_util.py", line 45, in <module>
    from .lib import pytree
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jax/lib/__init__.py", line 51, in <module>
    from jaxlib import xla_client
  File "/home/jerrhe/miniconda3/envs/saferew/lib/python3.6/site-packages/jaxlib/xla_client.py", line 37, in <module>
    from . import xla_extension as _xla
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
```

**Comment by hzyjerry** [comment]
Sorry for the spam. This is not an issue with numpyro, but my local settings. Posting the solution here

```bash
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
