### ISSUE TITLE
Subsampling and Predictive

### ISSUE THREAD

**Issue by AndreRoehrig** [pyro-ppl/numpyro#928]
I'm getting an error when I'm trying to sample using Predictive after running inference with a NUTS/MCMC setup and a model that uses subsampling. I tested the same without subsampling and I can run it successfully.

Code with subsampling:
```Python
import numpyro
from numpyro.infer import MCMC, NUTS, Predictive
import numpyro.distributions as dist
from jax import random
import numpy as np


def model(data=None):
    mu = numpyro.sample("beta", dist.Normal(0, 100.))
    sigma = numpyro.sample("global_sigma", dist.HalfNormal(10))
    with numpyro.plate("data", 1000, subsample_size=100):
        batch = numpyro.subsample(data, event_dim=0)
        numpyro.sample("obs", dist.Normal(mu, sigma),
                       obs=batch)


data = np.random.normal(0, 1, (1000, 1))
nuts_kernel = NUTS(model)

mcmc = MCMC(nuts_kernel, num_samples=100, num_warmup=100)
rng_key = random.PRNGKey(0)
mcmc.run(rng_key, data=data)
mcmc.print_summary(exclude_deterministic=False)
posterior_samples = mcmc.get_samples()

predictive = Predictive(model, posterior_samples,
                        return_sites=['obs'])

samples_predictive = predictive(random.PRNGKey(0), data=None)
```

Error:
```
Traceback (most recent call last):
  File "error.py", line 29, in <module>
    samples_predictive = predictive(random.PRNGKey(0), data=None)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/infer/util.py", line 611, in __call__
    return _predictive(rng_key, model, posterior_samples, self._batch_shape,
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/infer/util.py", line 514, in _predictive
    return soft_vmap(single_prediction, (rng_key, posterior_samples), len(batch_shape), chunk_size)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/util.py", line 308, in soft_vmap
    ys = lax.map(fn, xs) if num_chunks > 1 else fn(xs)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1908, in map
    _, ys = scan(g, (), xs)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1257, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1244, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(f, in_tree, carry_avals + x_avals)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 72, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(fun, in_tree, in_avals)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 67, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1191, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1201, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/andre/dev/.env/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 1907, in <lambda>
    g = lambda _, x: ((), f(x))
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/infer/util.py", line 497, in single_prediction
    model_trace = trace(seed(substitute(model, samples), rng_key)).get_trace(
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/handlers.py", line 161, in get_trace
    self(*args, **kwargs)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/primitives.py", line 81, in __call__
    return self.fn(*args, **kwargs)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/primitives.py", line 81, in __call__
    return self.fn(*args, **kwargs)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/primitives.py", line 81, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "error.py", line 12, in model
    batch = numpyro.subsample(data, event_dim=0)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/primitives.py", line 473, in subsample
    msg = apply_stack(initial_msg)
  File "/home/andre/dev/.env/lib/python3.8/site-packages/numpyro/primitives.py", line 36, in apply_stack
    msg['value'] = msg['fn'](*msg['args'], **msg['kwargs'])
KeyError: 'fn'
```
Working example without subsampling:
```Python
def model(data=None):
    mu = numpyro.sample("beta", dist.Normal(0, 100.))
    sigma = numpyro.sample("global_sigma", dist.HalfNormal(10))
    with numpyro.plate("data", 1000):
        numpyro.sample("obs", dist.Normal(mu, sigma),
                       obs=data)


data = np.random.normal(0, 1, (1000, 1))
nuts_kernel = NUTS(model)

mcmc = MCMC(nuts_kernel, num_samples=100, num_warmup=100)
rng_key = random.PRNGKey(0)
mcmc.run(rng_key, data=data)
mcmc.print_summary(exclude_deterministic=False)
posterior_samples = mcmc.get_samples()

predictive = Predictive(model, posterior_samples,
                        return_sites=['obs'])

samples_predictive = predictive(random.PRNGKey(0), data=None)
```

**Comment by fehiepsi** [comment]
Hi @AndreRoehrig, thanks for a clear report! I think you need something like
```
batch = numpyro.subsample(data, event_dim=0) if data is not None else None
```

You probably don't want subsample in predictive, so you can change plate statement into
```
with numpyro.plate("data", 1000, subsample_size=100 if data is not None else None):
```

Btw, NUTS uses a constant set of subsample indices in inference, so it will not work as you expected. You can wrap it with [HMCECS](http://num.pyro.ai/en/stable/mcmc.html?highlight=hmcecs#numpyro.infer.hmc_gibbs.HMCECS) as in [covtype example](https://github.com/pyro-ppl/numpyro/blob/5004691a4e4d5b3f10b0f4114096d5dfc5f8599c/examples/covtype.py#L84) if you want to do subsampling HMC.

**Comment by AndreRoehrig** [comment]
Thanks, your answer helped me get this working.
